### ISSUE TITLE
SPA JQuery wrong validation of credentials

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-jquery-samples#48]
In the JQuery quickstart, the validation of credentials to show some options and the message indicating that you're already logged in only considerates the "expires_at" field. 

I was able to manually generate and set this time on the browser's local storage, then I was able to access the options for a logged in user:

![capture](https://user-images.githubusercontent.com/15782359/33845758-d9198338-de7a-11e7-8628-71ecdc4155f2.jpg)

**Comment by aaguiarz** [comment]
Yes, that's fine. If you change that, even if it will look that you are logged-in in the web application, you will not be able to call any API as the access_token will be expired once it actually expires.
