### ISSUE TITLE
Error while trying to renew the token

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-jquery-samples#51]
When trying to renew the token, the call to the authorization API fails with a 400 error code.

![image](https://user-images.githubusercontent.com/15782359/34530162-a6682a7c-f084-11e7-88e1-259d37487d35.png)

**Comment by aaguiarz** [comment]
@rafanog Did you set the 'Web Origins' property in the tenant?

**Comment by rafanog** [comment]
@aaguiarz configured the parameter and it worked, thanks, I'll close this one
